requirementDiagram
    requirement r1 {
        id: 1
        text: some text
        risk: high
        verifymethod: test
    }
    element e1 {
        type: sim
        docref: d
    }
    e1 - satisfies -> r1
