// Copyright (c) 2026 Joel Baumert. All Rights Reserved.

pub mod activity;
pub mod admin;
pub mod ask;
pub mod audit;
pub mod auth;
pub mod chat;
pub mod client_telemetry;
pub mod comments;
pub mod documents;
pub mod folders;
pub mod history;
pub mod jobs;
pub mod metrics;
pub mod mfa;
pub mod notifications;
pub mod relationships;
pub mod saml;
pub mod scim;
pub mod search;
pub mod sharing;
pub mod slash_commands;
pub mod template_galleries;
pub mod users;
pub mod workspaces;
pub mod ws;

use axum::http::{HeaderName, HeaderValue};
use axum::Router;
use axum::routing::get;
use tower_http::set_header::SetResponseHeaderLayer;
use crate::state::AppState;

/// Build the Content-Security-Policy string. `extra_script_hashes`
/// is a list of base64-encoded SHA-256 digests (without the
/// `'sha256-'` wrapper) of inline `<script>` blocks the served
/// `index.html` is allowed to execute. Trunk emits exactly one such
/// block to bootstrap the WASM bundle, and its body changes whenever
/// the cache-busted JS filename rotates — `compute_inline_script_hashes`
/// pulls it out at server startup so the hash always matches the
/// shipped bundle.
///
/// Edit with care — Leptos requires 'wasm-unsafe-eval' on
/// `script-src` and inline-style attributes are generated by the
/// editor (selection rendering, cursor overlay), hence
/// `'unsafe-inline'` on `style-src`.
pub fn build_csp(extra_script_hashes: &[String]) -> String {
    let script_src = if extra_script_hashes.is_empty() {
        "'self' 'wasm-unsafe-eval'".to_string()
    } else {
        let hashes: Vec<String> = extra_script_hashes
            .iter()
            .map(|h| format!("'sha256-{h}'"))
            .collect();
        format!("'self' 'wasm-unsafe-eval' {}", hashes.join(" "))
    };
    format!(
        "default-src 'self'; \
         script-src {script_src}; \
         style-src 'self' 'unsafe-inline'; \
         img-src 'self' data: https:; \
         connect-src 'self' https:; \
         font-src 'self' data:; \
         frame-src {frame_src}; \
         frame-ancestors 'none'; \
         base-uri 'self'; \
         form-action 'self'",
        frame_src = embed_frame_src(),
    )
    // connect-src note: `'self'` covers same-origin WebSocket
    // (`wss://`) per CSP3 — the frontend WS endpoint is same-origin
    // to the SPA, so no explicit `wss:` token is needed. Listing
    // `wss:` would broaden the exfiltration surface to *any* WSS
    // host under XSS.
}

/// CSP without any inline-script allowance. Used by the integration
/// test harness, which doesn't serve the frontend bundle and never
/// emits inline scripts — and by callers that only need to know the
/// "base" policy. Production callers should always go through
/// `build_csp(&hashes)` so Trunk's bootstrap stays executable.
pub fn security_csp() -> String {
    build_csp(&[])
}

/// `frame-src` allowlist for sandboxed embeds (Phase 5 M-P6 piece
/// C). Each entry is an origin string (scheme + host) — CSP3 then
/// allows any path on that origin. The set mirrors the providers
/// `crates/api/src/embed_allowlist.rs::validate_url` recognizes;
/// adding a new provider there requires bumping this function in
/// the same change so the iframe actually loads.
///
/// Per-workspace allowed_domains aren't included here because the
/// CSP is computed once at server startup, before any request
/// context. Generic embeds are deferred to a future per-response
/// CSP override (or a separate "embed-domains" admin endpoint
/// that emits a workspace-scoped CSP at iframe-load time).
fn embed_frame_src() -> &'static str {
    // 'self' permits embeds we host directly (none today, but
    // keeps the iframe-from-our-origin case safe if a future
    // embed UX ever needs it).
    "'self' \
     https://www.youtube.com \
     https://player.vimeo.com \
     https://www.figma.com \
     https://www.loom.com \
     https://codesandbox.io"
}

/// Scan an HTML document for inline `<script>` blocks (i.e. those
/// without a `src=` attribute) and return the base64 SHA-256 of each
/// body, matching the form CSP3 expects in `'sha256-…'` source
/// expressions. Trunk emits exactly one such block to load the WASM;
/// computing the hash at startup keeps the CSP in sync with whatever
/// cache-busted bundle filename was emitted by the build, without
/// having to hand-update a constant on every release.
///
/// The HTML parser is intentionally a small hand-written scanner
/// rather than pulling in `scraper` / `html5ever` — the input is the
/// Trunk template we control, the only `<script>` blocks we care about
/// are the bootstrap, and a real HTML parser would be a 500KB+
/// transitive dep just to compute one hash at startup.
pub fn compute_inline_script_hashes(html: &str) -> Vec<String> {
    use base64::{engine::general_purpose::STANDARD, Engine as _};
    use sha2::{Digest, Sha256};

    let mut out = Vec::new();
    let bytes = html.as_bytes();
    let mut i = 0;
    while i + 7 < bytes.len() {
        // Locate the next `<script` (case-sensitive — Trunk lowercases).
        let Some(rel) = html[i..].find("<script") else { break };
        let tag_start = i + rel;
        // Find the closing `>` of the opening tag.
        let Some(rel_end) = html[tag_start..].find('>') else { break };
        let body_start = tag_start + rel_end + 1;
        let opening_tag = &html[tag_start..body_start];
        // External scripts (`src="…"`) carry no inline body to hash.
        if opening_tag.contains(" src=") || opening_tag.contains(" src ") {
            i = body_start;
            continue;
        }
        // Find the matching `</script>`.
        let Some(rel_close) = html[body_start..].find("</script>") else { break };
        let body_end = body_start + rel_close;
        let body = &html[body_start..body_end];

        let mut hasher = Sha256::new();
        hasher.update(body.as_bytes());
        out.push(STANDARD.encode(hasher.finalize()));

        i = body_end + "</script>".len();
    }
    out
}

/// Decide whether a request that missed every static file should be
/// answered with the SPA shell (`index.html`) or a `404`.
///
/// The frontend ships content-hashed asset filenames. After a deploy,
/// a returning client (or its service worker) may still ask for an
/// asset filename from a *previous* build — that file no longer exists
/// on disk. Such a request must `404` so the browser treats it as a
/// hard failure. The old behaviour of falling back to `index.html` for
/// *every* miss returned an HTML body (HTTP 200, `text/html`) for a
/// `*.js`/`*.wasm`/`*.css` URL; the browser then hashed that HTML
/// against the asset's Subresource-Integrity attribute, the check
/// failed, and the whole app refused to boot.
///
/// We key off the `Accept` header rather than the file extension:
/// top-level navigations send `Accept: text/html…` and legitimately
/// want the SPA shell (so client-side routes like `/d/<id>/doc` work);
/// sub-resource fetches (`<script>`, `<link>`, `fetch`) send `*/*`,
/// `text/css`, etc., and a miss there is a genuine 404.
pub fn spa_fallback_should_serve_shell(accept_header: Option<&str>) -> bool {
    accept_header.is_some_and(|a| a.contains("text/html"))
}

/// Apply the security-headers stack to a built router. Used by both
/// `main` and the integration test harness so the headers are
/// asserted under the same configuration as production. Closes #35.
///
/// `dev_mode = true` drops `Strict-Transport-Security` (which would
/// otherwise make a browser refuse `http://localhost` for a year
/// after a single visit). Every other header is on regardless.
///
/// `csp` is the full Content-Security-Policy string — production
/// callers should build it via `build_csp(&compute_inline_script_hashes(html))`
/// so the `<script>` Trunk emits to load the WASM is allowed; tests
/// that don't serve the frontend can pass `&security_csp()` for the
/// base policy.
pub fn apply_security_headers<S: Clone + Send + Sync + 'static>(
    router: Router<S>,
    dev_mode: bool,
    csp: &str,
) -> Router<S> {
    let csp_value = HeaderValue::from_str(csp).expect("CSP contains invalid header bytes");
    let mut router = router
        .layer(SetResponseHeaderLayer::if_not_present(
            HeaderName::from_static("content-security-policy"),
            csp_value,
        ))
        .layer(SetResponseHeaderLayer::if_not_present(
            HeaderName::from_static("x-content-type-options"),
            HeaderValue::from_static("nosniff"),
        ))
        .layer(SetResponseHeaderLayer::if_not_present(
            HeaderName::from_static("x-frame-options"),
            HeaderValue::from_static("DENY"),
        ))
        .layer(SetResponseHeaderLayer::if_not_present(
            HeaderName::from_static("referrer-policy"),
            HeaderValue::from_static("strict-origin-when-cross-origin"),
        ))
        .layer(SetResponseHeaderLayer::if_not_present(
            HeaderName::from_static("permissions-policy"),
            HeaderValue::from_static("camera=(), microphone=(), geolocation=()"),
        ));
    if !dev_mode {
        router = router.layer(SetResponseHeaderLayer::if_not_present(
            HeaderName::from_static("strict-transport-security"),
            HeaderValue::from_static("max-age=31536000; includeSubDomains"),
        ));
    }
    router
}

/// Build the complete API router.
/// Global cap on request body size — see `api_router` (#42).
///
/// Routes that intentionally need larger payloads (document content
/// writes, document import, multipart import) attach their own
/// `DefaultBodyLimit::max(...)` layer with the route-specific cap;
/// the inner per-route layer overrides this outer default. Every
/// other route handles small JSON bodies (auth, sharing, comments,
/// folders, metrics, admin) and fits comfortably inside this cap.
const GLOBAL_BODY_LIMIT_BYTES: usize = 1024 * 1024;

pub fn api_router() -> Router<AppState> {
    Router::new()
        .route("/health", get(|| async { "ok" }))
        .nest("/api/v1/auth", auth::router())
        .nest("/api/v1/users", users::router())
        .nest("/api/v1/documents", documents::router().merge(ws::router()).merge(comments::doc_router()).merge(history::router()).merge(sharing::doc_sharing_router()).merge(activity::router()).merge(relationships::doc_relationships_router()))
        .nest("/api/v1/threads", comments::thread_router())
        .nest("/api/v1/chats", chat::router())
        .nest("/api/v1/notifications", notifications::router())
        .nest("/api/v1/folders", folders::router().merge(sharing::router()))
        .nest("/api/v1/workspaces", workspaces::router())
        .nest("/api/v1/search", search::router())
        .nest("/api/v1/ask", ask::router())
        .nest("/api/v1/jobs", jobs::router())
        .nest("/api/v1/admin", admin::router().merge(template_galleries::router()))
        .nest("/api/v1/metrics", metrics::router())
        .nest("/api/v1/client-telemetry", client_telemetry::router())
        .nest("/api/v1/scim/v2", scim::router())
        // Global body-size cap (#42). Axum's default for typed
        // extractors is 2 MiB; raw `Bytes` and `Multipart` are
        // unbounded by default. Set a single explicit cap here so
        // every state-changing route has a known ceiling without
        // each handler needing to repeat itself. Routes that
        // legitimately accept larger bodies (PUT /documents/:id/
        // content, POST /documents/import{-job}, POST /documents/
        // :id/import) override with their own per-route layer —
        // see `documents::router`. Pre-merge this was an inconsistent
        // ratchet: most routes inherited axum's 2 MiB; multipart
        // routes were unbounded.
        .layer(axum::extract::DefaultBodyLimit::max(GLOBAL_BODY_LIMIT_BYTES))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn csp_contains_frame_src_with_embed_providers() {
        let csp = build_csp(&[]);
        assert!(csp.contains("frame-src"), "csp missing frame-src: {csp}");
        for origin in [
            "https://www.youtube.com",
            "https://player.vimeo.com",
            "https://www.figma.com",
            "https://www.loom.com",
            "https://codesandbox.io",
        ] {
            assert!(csp.contains(origin), "frame-src missing {origin}: {csp}");
        }
        // frame-ancestors stays 'none' so we still can't be embedded
        // by a third party.
        assert!(csp.contains("frame-ancestors 'none'"), "got: {csp}");
    }

    #[test]
    fn csp_inline_script_hashes_still_added_alongside_frame_src() {
        let csp = build_csp(&["AABBCC".to_string()]);
        assert!(csp.contains("'sha256-AABBCC'"), "got: {csp}");
        assert!(csp.contains("frame-src"), "got: {csp}");
    }

    #[test]
    fn spa_fallback_404s_stale_asset_requests_but_serves_shell_to_navigations() {
        // A stale client asking for a content-hashed asset from a prior
        // deploy sends `Accept: */*` (sub-resource fetch) — it must 404,
        // not receive index.html (which would fail the asset's SRI check
        // and brick the app). Regression for the doc-load failure where
        // an empty/HTML body was hashed against a sha384 integrity attr.
        assert!(
            !spa_fallback_should_serve_shell(Some("*/*")),
            "asset-style fetch must 404, not get the SPA shell"
        );
        assert!(
            !spa_fallback_should_serve_shell(Some("text/css,*/*;q=0.1")),
            "stylesheet fetch must 404, not get the SPA shell"
        );
        assert!(
            !spa_fallback_should_serve_shell(None),
            "header-less fetch must 404, not get the SPA shell"
        );

        // Top-level navigations want the shell so client-side routes
        // (e.g. /d/<id>/doc) keep working.
        assert!(
            spa_fallback_should_serve_shell(Some(
                "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
            )),
            "navigation must receive the SPA shell"
        );
    }
}
