// Copyright (c) 2026 Joel Baumert. All Rights Reserved.

//! Symbol commands: what `\alpha`, `\leq`, `\sum`, `\sin`, … produce.

/// How a symbol command renders.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Sym {
    /// `<mi>`, italic when a single Latin/Greek letter (lowercase Greek).
    Ident(char),
    /// `<mi mathvariant="normal">` (uppercase Greek).
    Upright(char),
    /// `<mo>`: binary operators, relations, arrows, punctuation.
    Op(char),
    /// A delimiter; `<mo stretchy="false">` unless sized by `\left`/`\big`.
    Delim(char),
    /// Big operator whose limits go above/below in display style (`\sum`).
    BigOp(char),
    /// Integral: limits stay as sub/superscripts unless `\limits`.
    Integral(char),
}

pub(crate) fn symbol(name: &str) -> Option<Sym> {
    use Sym::*;
    Some(match name {
        // Greek, lowercase (italic).
        "alpha" => Ident('α'),
        "beta" => Ident('β'),
        "gamma" => Ident('γ'),
        "delta" => Ident('δ'),
        "epsilon" => Ident('ϵ'),
        "varepsilon" => Ident('ε'),
        "zeta" => Ident('ζ'),
        "eta" => Ident('η'),
        "theta" => Ident('θ'),
        "vartheta" => Ident('ϑ'),
        "iota" => Ident('ι'),
        "kappa" => Ident('κ'),
        "varkappa" => Ident('ϰ'),
        "lambda" => Ident('λ'),
        "mu" => Ident('μ'),
        "nu" => Ident('ν'),
        "xi" => Ident('ξ'),
        "omicron" => Ident('ο'),
        "pi" => Ident('π'),
        "varpi" => Ident('ϖ'),
        "rho" => Ident('ρ'),
        "varrho" => Ident('ϱ'),
        "sigma" => Ident('σ'),
        "varsigma" => Ident('ς'),
        "tau" => Ident('τ'),
        "upsilon" => Ident('υ'),
        "phi" => Ident('ϕ'),
        "varphi" => Ident('φ'),
        "chi" => Ident('χ'),
        "psi" => Ident('ψ'),
        "omega" => Ident('ω'),
        "digamma" => Ident('ϝ'),
        // Greek, uppercase (upright, as in LaTeX).
        "Gamma" => Upright('Γ'),
        "Delta" => Upright('Δ'),
        "Theta" => Upright('Θ'),
        "Lambda" => Upright('Λ'),
        "Xi" => Upright('Ξ'),
        "Pi" => Upright('Π'),
        "Sigma" => Upright('Σ'),
        "Upsilon" => Upright('Υ'),
        "Phi" => Upright('Φ'),
        "Psi" => Upright('Ψ'),
        "Omega" => Upright('Ω'),
        // Letter-like and ordinary symbols.
        "infty" => Ident('∞'),
        "partial" => Ident('∂'),
        "nabla" => Ident('∇'),
        "emptyset" | "varnothing" => Ident('∅'),
        "aleph" => Ident('ℵ'),
        "beth" => Ident('ℶ'),
        "hbar" | "hslash" => Ident('ℏ'),
        "ell" => Ident('ℓ'),
        "imath" => Ident('ı'),
        "jmath" => Ident('ȷ'),
        "Re" => Ident('ℜ'),
        "Im" => Ident('ℑ'),
        "wp" => Ident('℘'),
        "mho" => Ident('℧'),
        "eth" => Ident('ð'),
        "top" => Ident('⊤'),
        "bot" => Ident('⊥'),
        "angle" => Ident('∠'),
        "measuredangle" => Ident('∡'),
        "triangle" => Ident('△'),
        "square" | "Box" => Ident('□'),
        "blacksquare" => Ident('■'),
        "Diamond" => Ident('◇'),
        "lozenge" => Ident('◊'),
        "clubsuit" => Ident('♣'),
        "diamondsuit" => Ident('♢'),
        "heartsuit" => Ident('♡'),
        "spadesuit" => Ident('♠'),
        "flat" => Ident('♭'),
        "natural" => Ident('♮'),
        "sharp" => Ident('♯'),
        "checkmark" => Ident('✓'),
        "complement" => Ident('∁'),
        "S" => Ident('§'),
        "P" => Ident('¶'),
        "degree" => Ident('°'),
        // Logic and quantifiers.
        "forall" => Op('∀'),
        "exists" => Op('∃'),
        "nexists" => Op('∄'),
        "neg" | "lnot" => Op('¬'),
        "therefore" => Op('∴'),
        "because" => Op('∵'),
        // Binary operators.
        "pm" => Op('±'),
        "mp" => Op('∓'),
        "times" => Op('×'),
        "div" => Op('÷'),
        "cdot" | "cdotp" | "centerdot" => Op('⋅'),
        "ast" => Op('∗'),
        "star" => Op('⋆'),
        "circ" => Op('∘'),
        "bullet" => Op('∙'),
        "oplus" => Op('⊕'),
        "ominus" => Op('⊖'),
        "otimes" => Op('⊗'),
        "oslash" => Op('⊘'),
        "odot" => Op('⊙'),
        "cup" => Op('∪'),
        "cap" => Op('∩'),
        "sqcup" => Op('⊔'),
        "sqcap" => Op('⊓'),
        "uplus" => Op('⊎'),
        "wedge" | "land" => Op('∧'),
        "vee" | "lor" => Op('∨'),
        "setminus" | "smallsetminus" => Op('∖'),
        "wr" => Op('≀'),
        "diamond" => Op('⋄'),
        "bigtriangleup" => Op('△'),
        "bigtriangledown" => Op('▽'),
        "triangleleft" => Op('◃'),
        "triangleright" => Op('▹'),
        "lhd" => Op('⊲'),
        "rhd" => Op('⊳'),
        "unlhd" => Op('⊴'),
        "unrhd" => Op('⊵'),
        "amalg" => Op('⨿'),
        "dagger" => Op('†'),
        "ddagger" => Op('‡'),
        "bigcirc" => Op('◯'),
        "ltimes" => Op('⋉'),
        "rtimes" => Op('⋊'),
        "dotplus" => Op('∔'),
        "intercal" => Op('⊺'),
        // Relations.
        "leq" | "le" => Op('≤'),
        "geq" | "ge" => Op('≥'),
        "neq" | "ne" => Op('≠'),
        "equiv" => Op('≡'),
        "approx" => Op('≈'),
        "approxeq" => Op('≊'),
        "cong" => Op('≅'),
        "sim" => Op('∼'),
        "simeq" => Op('≃'),
        "propto" => Op('∝'),
        "ll" => Op('≪'),
        "gg" => Op('≫'),
        "lll" => Op('⋘'),
        "ggg" => Op('⋙'),
        "prec" => Op('≺'),
        "succ" => Op('≻'),
        "preceq" => Op('⪯'),
        "succeq" => Op('⪰'),
        "subset" => Op('⊂'),
        "supset" => Op('⊃'),
        "subseteq" => Op('⊆'),
        "supseteq" => Op('⊇'),
        "subsetneq" => Op('⊊'),
        "supsetneq" => Op('⊋'),
        "sqsubset" => Op('⊏'),
        "sqsupset" => Op('⊐'),
        "sqsubseteq" => Op('⊑'),
        "sqsupseteq" => Op('⊒'),
        "in" => Op('∈'),
        "ni" | "owns" => Op('∋'),
        "notin" => Op('∉'),
        "mid" => Op('∣'),
        "nmid" => Op('∤'),
        "parallel" => Op('∥'),
        "nparallel" => Op('∦'),
        "perp" => Op('⊥'),
        "vdash" => Op('⊢'),
        "dashv" => Op('⊣'),
        "models" => Op('⊨'),
        "doteq" => Op('≐'),
        "asymp" => Op('≍'),
        "bowtie" => Op('⋈'),
        "smile" => Op('⌣'),
        "frown" => Op('⌢'),
        "leqslant" => Op('⩽'),
        "geqslant" => Op('⩾'),
        "lesssim" => Op('≲'),
        "gtrsim" => Op('≳'),
        "nless" => Op('≮'),
        "ngtr" => Op('≯'),
        "nleq" => Op('≰'),
        "ngeq" => Op('≱'),
        "triangleq" => Op('≜'),
        "coloneqq" => Op('≔'),
        "eqqcolon" => Op('≕'),
        // Arrows.
        "to" | "rightarrow" => Op('→'),
        "gets" | "leftarrow" => Op('←'),
        "leftrightarrow" => Op('↔'),
        "Rightarrow" => Op('⇒'),
        "Leftarrow" => Op('⇐'),
        "Leftrightarrow" => Op('⇔'),
        "implies" | "Longrightarrow" => Op('⟹'),
        "impliedby" | "Longleftarrow" => Op('⟸'),
        "iff" | "Longleftrightarrow" => Op('⟺'),
        "longrightarrow" => Op('⟶'),
        "longleftarrow" => Op('⟵'),
        "longleftrightarrow" => Op('⟷'),
        "mapsto" => Op('↦'),
        "longmapsto" => Op('⟼'),
        "hookrightarrow" => Op('↪'),
        "hookleftarrow" => Op('↩'),
        "uparrow" => Delim('↑'),
        "downarrow" => Delim('↓'),
        "updownarrow" => Delim('↕'),
        "Uparrow" => Delim('⇑'),
        "Downarrow" => Delim('⇓'),
        "Updownarrow" => Delim('⇕'),
        "nearrow" => Op('↗'),
        "searrow" => Op('↘'),
        "swarrow" => Op('↙'),
        "nwarrow" => Op('↖'),
        "rightharpoonup" => Op('⇀'),
        "rightharpoondown" => Op('⇁'),
        "leftharpoonup" => Op('↼'),
        "leftharpoondown" => Op('↽'),
        "rightleftharpoons" => Op('⇌'),
        "leftrightarrows" => Op('⇆'),
        "rightrightarrows" => Op('⇉'),
        "leadsto" => Op('⇝'),
        "nrightarrow" => Op('↛'),
        "nleftarrow" => Op('↚'),
        "nRightarrow" => Op('⇏'),
        "circlearrowleft" => Op('↺'),
        "circlearrowright" => Op('↻'),
        // Dots and punctuation.
        "ldots" | "dots" | "dotsc" | "dotso" => Op('…'),
        "cdots" | "dotsb" | "dotsm" | "dotsi" => Op('⋯'),
        "vdots" => Op('⋮'),
        "ddots" => Op('⋱'),
        "colon" => Op(':'),
        "prime" => Op('′'),
        "backslash" => Delim('\\'),
        // Delimiters.
        "langle" => Delim('⟨'),
        "rangle" => Delim('⟩'),
        "lbrace" => Delim('{'),
        "rbrace" => Delim('}'),
        "lbrack" => Delim('['),
        "rbrack" => Delim(']'),
        "lfloor" => Delim('⌊'),
        "rfloor" => Delim('⌋'),
        "lceil" => Delim('⌈'),
        "rceil" => Delim('⌉'),
        "vert" | "lvert" | "rvert" => Delim('|'),
        "Vert" | "lVert" | "rVert" => Delim('‖'),
        "ulcorner" => Delim('⌜'),
        "urcorner" => Delim('⌝'),
        "llcorner" => Delim('⌞'),
        "lrcorner" => Delim('⌟'),
        "lgroup" => Delim('⟮'),
        "rgroup" => Delim('⟯'),
        // Big operators.
        "sum" => BigOp('∑'),
        "prod" => BigOp('∏'),
        "coprod" => BigOp('∐'),
        "bigcup" => BigOp('⋃'),
        "bigcap" => BigOp('⋂'),
        "bigvee" => BigOp('⋁'),
        "bigwedge" => BigOp('⋀'),
        "bigoplus" => BigOp('⨁'),
        "bigotimes" => BigOp('⨂'),
        "bigodot" => BigOp('⨀'),
        "biguplus" => BigOp('⨄'),
        "bigsqcup" => BigOp('⨆'),
        "int" | "intop" | "smallint" => Integral('∫'),
        "iint" => Integral('∬'),
        "iiint" => Integral('∭'),
        "iiiint" => Integral('⨌'),
        "oint" => Integral('∮'),
        "oiint" => Integral('∯'),
        _ => return None,
    })
}

/// Named functions set upright and followed by function application
/// (`\sin x`). Limits, if any, go to the side.
pub(crate) fn function(name: &str) -> Option<&'static str> {
    Some(match name {
        "arccos" => "arccos",
        "arcsin" => "arcsin",
        "arctan" => "arctan",
        "arcsec" => "arcsec",
        "arccot" => "arccot",
        "arccsc" => "arccsc",
        "arg" => "arg",
        "cos" => "cos",
        "cosh" => "cosh",
        "cot" => "cot",
        "coth" => "coth",
        "csc" => "csc",
        "csch" => "csch",
        "deg" => "deg",
        "dim" => "dim",
        "exp" => "exp",
        "hom" => "hom",
        "ker" => "ker",
        "lg" => "lg",
        "ln" => "ln",
        "log" => "log",
        "sec" => "sec",
        "sech" => "sech",
        "sin" => "sin",
        "sinh" => "sinh",
        "tan" => "tan",
        "tanh" => "tanh",
        _ => return None,
    })
}

/// Named functions whose limits go underneath in display style
/// (`\lim_{x \to 0}`).
pub(crate) fn limit_function(name: &str) -> Option<&'static str> {
    Some(match name {
        "lim" => "lim",
        "limsup" => "lim sup",
        "liminf" => "lim inf",
        "max" => "max",
        "min" => "min",
        "sup" => "sup",
        "inf" => "inf",
        "det" => "det",
        "gcd" => "gcd",
        "Pr" => "Pr",
        "injlim" => "inj lim",
        "projlim" => "proj lim",
        _ => return None,
    })
}

/// Accent commands: (character, stretches across a wide base?, below?).
pub(crate) fn accent(name: &str) -> Option<(char, bool, bool)> {
    Some(match name {
        "hat" => ('^', false, false),
        "widehat" => ('^', true, false),
        "check" => ('ˇ', false, false),
        "widecheck" => ('ˇ', true, false),
        "tilde" => ('~', false, false),
        "widetilde" => ('~', true, false),
        "acute" => ('´', false, false),
        "grave" => ('`', false, false),
        "dot" => ('˙', false, false),
        "ddot" => ('¨', false, false),
        "dddot" => ('⃛', false, false),
        "breve" => ('˘', false, false),
        "bar" => ('¯', false, false),
        "vec" => ('→', false, false),
        "mathring" => ('˚', false, false),
        "overline" => ('‾', true, false),
        "overrightarrow" => ('→', true, false),
        "overleftarrow" => ('←', true, false),
        "overleftrightarrow" => ('↔', true, false),
        "underline" => ('_', true, true),
        "underrightarrow" => ('→', true, true),
        "underleftarrow" => ('←', true, true),
        "underleftrightarrow" => ('↔', true, true),
        _ => return None,
    })
}

/// A delimiter written after `\left`, `\right`, `\big`, …: its character,
/// or `None` for the empty delimiter `.`.
pub(crate) fn delimiter_char(c: char) -> Option<Option<char>> {
    Some(match c {
        '.' => None,
        '(' | ')' | '[' | ']' | '|' | '/' => Some(c),
        '<' => Some('⟨'),
        '>' => Some('⟩'),
        _ => return None,
    })
}

pub(crate) fn delimiter_command(name: &str) -> Option<char> {
    Some(match name {
        "{" | "lbrace" => '{',
        "}" | "rbrace" => '}',
        "|" | "Vert" | "lVert" | "rVert" => '‖',
        _ => match symbol(name) {
            Some(Sym::Delim(c)) => c,
            _ => return None,
        },
    })
}

/// The negated form of a relation for `\not`: a precomposed character
/// when Unicode has one, else the relation followed by U+0338.
pub(crate) fn negate(c: char) -> String {
    let composed = match c {
        '=' => '≠',
        '<' => '≮',
        '>' => '≯',
        '≤' => '≰',
        '≥' => '≱',
        '∈' => '∉',
        '∋' => '∌',
        '⊂' => '⊄',
        '⊃' => '⊅',
        '⊆' => '⊈',
        '⊇' => '⊉',
        '≡' => '≢',
        '∼' => '≁',
        '≈' => '≉',
        '≃' => '≄',
        '≅' => '≇',
        '∣' => '∤',
        '∥' => '∦',
        '→' => '↛',
        '←' => '↚',
        _ => return format!("{c}\u{338}"),
    };
    composed.to_string()
}
