// Copyright (c) 2026 Joel Baumert. All Rights Reserved.

//! Mermaid diagram live-app block (frontend). Renders the SVG produced
//! by `ogrenotes-mermaid`, or an error banner + raw source on failure.
//! Source lives in the `source` attribute; editing goes through the
//! Mermaid modal (see `components::mermaid_modal`).

use std::cell::RefCell;
use std::collections::{HashMap, VecDeque};

use web_sys::{Document, Node as DomNode};

use super::super::model::{Fragment, Node, NodeType};
use super::{LiveAppBlockInsert, LiveAppBlockView};

pub struct MermaidView;
pub struct MermaidInsert;

/// Rendered diagrams kept by source, most recent first.
const RENDER_CACHE_CAP: usize = 32;

thread_local! {
    static RENDER_CACHE: RefCell<VecDeque<(String, Result<String, String>)>> =
        const { RefCell::new(VecDeque::new()) };
}

/// `ogrenotes_mermaid::render` memoized by source: SVG, or the error
/// message. The editor view rebuilds every block on every document
/// change — each keystroke, local or a collaborator's — so without this
/// every diagram in the doc re-parsed and re-laid-out per keystroke on
/// the main thread. A diagram's output depends only on its source.
fn render_cached(source: &str) -> Result<String, String> {
    RENDER_CACHE.with(|cache| {
        let mut cache = cache.borrow_mut();
        if let Some(i) = cache.iter().position(|(s, _)| s == source) {
            let hit = cache.remove(i).expect("index from position");
            let out = hit.1.clone();
            cache.push_front(hit);
            return out;
        }
        let rendered = ogrenotes_mermaid::render(source);
        let out = match rendered.svg {
            Some(svg) => Ok(svg),
            None => Err(rendered.error.map(|e| e.message).unwrap_or_else(|| "diagram error".into())),
        };
        cache.push_front((source.to_string(), out.clone()));
        cache.truncate(RENDER_CACHE_CAP);
        out
    })
}

const STARTER_SOURCE: &str = "pie title Pets\n\"Dogs\" : 386\n\"Cats\" : 85\n\"Birds\" : 15";

impl LiveAppBlockView for MermaidView {
    fn node_types(&self) -> &'static [NodeType] {
        &[NodeType::Mermaid]
    }

    fn render(
        &self,
        doc: &Document,
        _node_type: NodeType,
        attrs: &HashMap<String, String>,
        _content: &Fragment,
    ) -> Option<DomNode> {
        let source = attrs.get("source").map(String::as_str).unwrap_or("");
        let wrapper = doc.create_element("div").ok()?;
        wrapper.set_attribute("class", "mermaid-block").ok()?;
        wrapper.set_attribute("contenteditable", "false").ok()?;
        // Leaf atom of model size 1 — DOM↔model mapping treats it as opaque.
        wrapper.set_attribute("data-atom-size", "1").ok()?;
        if let Some(bid) = attrs.get("blockId") {
            wrapper.set_attribute("data-block-id", bid).ok()?;
        }
        // Edit hook consumed by the delegated click listener (Task 8).
        wrapper.set_attribute("data-mermaid-action", "edit").ok()?;
        // Current source, so the click listener can seed the edit
        // modal without a separate model lookup. `set_attribute`
        // escapes the value automatically.
        wrapper.set_attribute("data-source", source).ok()?;

        match render_cached(source) {
            Ok(svg) => {
                let holder = doc.create_element("div").ok()?;
                holder.set_attribute("class", "mermaid-svg").ok()?;
                // Trusted: SVG is generated by our renderer with the
                // source XML-escaped internally.
                holder.set_inner_html(&svg);
                wrapper.append_child(&holder).ok()?;
            }
            Err(msg) => {
                let banner = doc.create_element("p").ok()?;
                banner.set_attribute("class", "mermaid-error").ok()?;
                banner.set_text_content(Some(&msg));
                let pre = doc.create_element("pre").ok()?;
                // Untrusted source — text content, never inner_html.
                pre.set_text_content(Some(source));
                wrapper.append_child(&banner).ok()?;
                wrapper.append_child(&pre).ok()?;
            }
        }
        Some(wrapper.into())
    }
}

impl LiveAppBlockInsert for MermaidInsert {
    fn id(&self) -> &'static str {
        "mermaid"
    }
    fn label_key(&self) -> &'static str {
        "insert-mermaid-label"
    }
    fn description_key(&self) -> &'static str {
        "insert-mermaid-description"
    }
    fn icon(&self) -> &'static str {
        "\u{1F4CA}" // 📊
    }
    fn build_default_node(&self) -> Node {
        let mut attrs = HashMap::new();
        attrs.insert("source".to_string(), STARTER_SOURCE.to_string());
        Node::element_with_attrs(NodeType::Mermaid, attrs, Fragment::empty())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_cache_returns_the_same_output_and_stays_bounded() {
        let pie = "pie\n\"A\" : 1\n\"B\" : 2";
        let first = render_cached(pie);
        assert!(first.as_ref().is_ok_and(|svg| svg.starts_with("<svg")));
        assert_eq!(render_cached(pie), first);
        assert!(render_cached("not a diagram").is_err());
        for i in 0..RENDER_CACHE_CAP * 2 {
            let _ = render_cached(&format!("pie\n\"A{i}\" : 1"));
        }
        RENDER_CACHE.with(|c| assert_eq!(c.borrow().len(), RENDER_CACHE_CAP));
        // An evicted entry renders again, identically.
        assert_eq!(render_cached(pie), first);
    }
}
