// Copyright (c) 2026 Joel Baumert. All Rights Reserved.

//! Mermaid diagram live-app block (frontend). Renders the SVG produced
//! by `ogrenotes-mermaid`, or an error banner + raw source on failure.
//! Source lives in the `source` attribute; editing goes through the
//! Mermaid modal (see `components::mermaid_modal`).

use std::collections::HashMap;

use web_sys::{Document, Node as DomNode};

use super::super::model::{Fragment, Node, NodeType};
use super::{LiveAppBlockInsert, LiveAppBlockView};

pub struct MermaidView;
pub struct MermaidInsert;

const STARTER_SOURCE: &str = "pie title Pets\n\"Dogs\" : 386\n\"Cats\" : 85\n\"Birds\" : 15";

impl LiveAppBlockView for MermaidView {
    fn node_types(&self) -> &'static [NodeType] {
        &[NodeType::Mermaid]
    }

    fn render(
        &self,
        doc: &Document,
        _node_type: NodeType,
        attrs: &HashMap<String, String>,
        _content: &Fragment,
    ) -> Option<DomNode> {
        let source = attrs.get("source").map(String::as_str).unwrap_or("");
        let wrapper = doc.create_element("div").ok()?;
        wrapper.set_attribute("class", "mermaid-block").ok()?;
        wrapper.set_attribute("contenteditable", "false").ok()?;
        // Leaf atom of model size 1 — DOM↔model mapping treats it as opaque.
        wrapper.set_attribute("data-atom-size", "1").ok()?;
        if let Some(bid) = attrs.get("blockId") {
            wrapper.set_attribute("data-block-id", bid).ok()?;
        }
        // Edit hook consumed by the delegated click listener (Task 8).
        wrapper.set_attribute("data-mermaid-action", "edit").ok()?;

        let out = ogrenotes_mermaid::render(source);
        match out.svg {
            Some(svg) => {
                let holder = doc.create_element("div").ok()?;
                holder.set_attribute("class", "mermaid-svg").ok()?;
                // Trusted: SVG is generated by our renderer with the
                // source XML-escaped internally.
                holder.set_inner_html(&svg);
                wrapper.append_child(&holder).ok()?;
            }
            None => {
                let msg = out.error.map(|e| e.message).unwrap_or_else(|| "diagram error".into());
                let banner = doc.create_element("p").ok()?;
                banner.set_attribute("class", "mermaid-error").ok()?;
                banner.set_text_content(Some(&msg));
                let pre = doc.create_element("pre").ok()?;
                // Untrusted source — text content, never inner_html.
                pre.set_text_content(Some(source));
                wrapper.append_child(&banner).ok()?;
                wrapper.append_child(&pre).ok()?;
            }
        }
        Some(wrapper.into())
    }
}

impl LiveAppBlockInsert for MermaidInsert {
    fn id(&self) -> &'static str {
        "mermaid"
    }
    fn label_key(&self) -> &'static str {
        "insert-mermaid-label"
    }
    fn description_key(&self) -> &'static str {
        "insert-mermaid-description"
    }
    fn icon(&self) -> &'static str {
        "\u{1F4CA}" // 📊
    }
    fn build_default_node(&self) -> Node {
        let mut attrs = HashMap::new();
        attrs.insert("source".to_string(), STARTER_SOURCE.to_string());
        Node::element_with_attrs(NodeType::Mermaid, attrs, Fragment::empty())
    }
}
